import type { Language } from '@/lib/language'

export const marketplaceTranslations: Record<Language, Record<string, string>> = {
  en: {
    navFindHelp: 'Find help', navBookings: 'My bookings', navBecomeHelper: 'Become a helper', navHelp: 'Help & contact', callSupport: 'Call support',
    homeBadge: 'Built for everyday life in Luxembourg', homeTitle: 'Trusted local help for you and your loved ones.', homeSubtitle: 'Find practical, friendly support from local people for everyday tasks, appointments, technology and companionship.', homeFindHelp: 'Find help near me', homeBecomeHelper: 'Become a helper', homeNoAccount: 'No account needed to browse. We only ask for your contact details when you confirm a booking.',
    homeSimpleTitle: 'Simple, safe and human.', homeStepOneTitle: '1. Tell us what is needed', homeStepOneCopy: 'Choose a service and an area. No login required.', homeStepTwoTitle: '2. Choose a suitable helper', homeStepTwoCopy: 'See availability, languages and practical details first.', homeStepThreeTitle: '3. Confirm with confidence', homeStepThreeCopy: 'Review the visit before sharing contact details.',
    homeEveryday: 'Everyday support', homeQuestion: 'What do you need help with today?', homeQuestionCopy: 'Choose a familiar task. You can browse helpers before making a booking.', homeSeeServices: 'See all services', homeFindHelpers: 'Find helpers', homeSafetyTitle: 'Clear safety information', homeSafetyCopy: 'Helpers must complete verification before a live marketplace launch.', homeIndependenceTitle: 'Built for independence', homeIndependenceCopy: 'Large controls, plain language and one clear next step at a time.', homeNeedBooking: 'Need a hand booking?', homeCallLine: 'Call support on',
    servicesEyebrow: 'Find help', servicesTitle: 'What do you need help with?', servicesCopy: 'Choose one service to see local helpers. You do not need an account to look.', servicesSeeHelpers: 'See helpers', servicesUnsure: 'Not sure which service to choose?', servicesUnsureCopy: 'Call us and we will help you choose the right type of support.',
    serviceGroceries: 'Groceries & pharmacy', serviceGroceriesCopy: 'Shopping, prescriptions and essential errands.', serviceCleaning: 'Cleaning & home care', serviceCleaningCopy: 'Light cleaning and practical help at home.', serviceCompanionship: 'Companionship visits', serviceCompanionshipCopy: 'A friendly visit, walk or chat nearby.', serviceAppointments: 'Appointment escort', serviceAppointmentsCopy: 'Company and transport support for appointments.', serviceTechnology: 'Technology help', serviceTechnologyCopy: 'Phones, computers, video calls and devices.', serviceRepairs: 'Small home tasks', serviceRepairsCopy: 'Light household tasks and small repairs.', serviceTransport: 'Rides & transport', serviceTransportCopy: 'Help getting safely around your area.', allServices: 'All services', allLanguages: 'All languages', communityHelper: 'Community helper', identityChecked: 'Identity checked', viewHelper: 'View helper', requestVisit: 'Request a visit'
  },
  fr: {
    navFindHelp: 'Trouver de l’aide', navBookings: 'Mes réservations', navBecomeHelper: 'Devenir aidant', navHelp: 'Aide et contact', callSupport: 'Appeler l’assistance',
    homeBadge: 'Pensé pour la vie quotidienne au Luxembourg', homeTitle: 'Une aide locale de confiance pour vous et vos proches.', homeSubtitle: 'Trouvez une aide pratique et bienveillante près de chez vous pour les tâches du quotidien, les rendez-vous, la technologie et la compagnie.', homeFindHelp: 'Trouver de l’aide près de chez moi', homeBecomeHelper: 'Devenir aidant', homeNoAccount: 'Aucun compte n’est nécessaire pour consulter les profils. Nous demandons vos coordonnées seulement lorsque vous confirmez une demande.',
    homeSimpleTitle: 'Simple, sûr et humain.', homeStepOneTitle: '1. Dites-nous ce dont vous avez besoin', homeStepOneCopy: 'Choisissez un service et une zone. Aucun compte n’est nécessaire.', homeStepTwoTitle: '2. Choisissez un aidant adapté', homeStepTwoCopy: 'Consultez d’abord les disponibilités, langues et informations pratiques.', homeStepThreeTitle: '3. Confirmez en toute confiance', homeStepThreeCopy: 'Vérifiez la visite avant de partager vos coordonnées.',
    homeEveryday: 'Aide au quotidien', homeQuestion: 'De quelle aide avez-vous besoin aujourd’hui ?', homeQuestionCopy: 'Choisissez une tâche familière. Vous pouvez consulter les aidants avant de réserver.', homeSeeServices: 'Voir tous les services', homeFindHelpers: 'Trouver des aidants', homeSafetyTitle: 'Informations de sécurité claires', homeSafetyCopy: 'Les aidants doivent terminer la vérification avant le lancement du service réel.', homeIndependenceTitle: 'Conçu pour l’autonomie', homeIndependenceCopy: 'De grands contrôles, un langage simple et une prochaine étape claire.', homeNeedBooking: 'Besoin d’aide pour réserver ?', homeCallLine: 'Appelez l’assistance au',
    servicesEyebrow: 'Trouver de l’aide', servicesTitle: 'De quelle aide avez-vous besoin ?', servicesCopy: 'Choisissez un service pour voir les aidants locaux. Aucun compte n’est nécessaire pour consulter.', servicesSeeHelpers: 'Voir les aidants', servicesUnsure: 'Vous ne savez pas quel service choisir ?', servicesUnsureCopy: 'Appelez-nous et nous vous aiderons à choisir le bon type de soutien.',
    serviceGroceries: 'Courses et pharmacie', serviceGroceriesCopy: 'Courses, ordonnances et déplacements essentiels.', serviceCleaning: 'Ménage et aide à domicile', serviceCleaningCopy: 'Ménage léger et aide pratique à la maison.', serviceCompanionship: 'Visites de compagnie', serviceCompanionshipCopy: 'Une visite, une promenade ou une conversation amicale.', serviceAppointments: 'Accompagnement aux rendez-vous', serviceAppointmentsCopy: 'Compagnie et aide au transport pour les rendez-vous.', serviceTechnology: 'Aide technologique', serviceTechnologyCopy: 'Téléphones, ordinateurs, appels vidéo et appareils.', serviceRepairs: 'Petites tâches à domicile', serviceRepairsCopy: 'Tâches ménagères légères et petites réparations.', serviceTransport: 'Trajets et transport', serviceTransportCopy: 'Une aide pour vous déplacer en sécurité dans votre quartier.', allServices: 'Tous les services', allLanguages: 'Toutes les langues', communityHelper: 'Aidant de la communauté', identityChecked: 'Identité vérifiée', viewHelper: 'Voir l’aidant', requestVisit: 'Demander une visite'
  },
  de: {
    navFindHelp: 'Hilfe finden', navBookings: 'Meine Buchungen', navBecomeHelper: 'Helfer werden', navHelp: 'Hilfe und Kontakt', callSupport: 'Support anrufen',
    homeBadge: 'Für den Alltag in Luxemburg', homeTitle: 'Verlässliche lokale Hilfe für Sie und Ihre Angehörigen.', homeSubtitle: 'Finden Sie praktische, freundliche Unterstützung aus der Nachbarschaft für alltägliche Aufgaben, Termine, Technik und Gesellschaft.', homeFindHelp: 'Hilfe in meiner Nähe finden', homeBecomeHelper: 'Helfer werden', homeNoAccount: 'Zum Stöbern ist kein Konto nötig. Ihre Kontaktdaten fragen wir erst bei der Bestätigung einer Anfrage ab.',
    homeSimpleTitle: 'Einfach, sicher und menschlich.', homeStepOneTitle: '1. Sagen Sie, was Sie brauchen', homeStepOneCopy: 'Wählen Sie einen Dienst und einen Ort. Keine Anmeldung nötig.', homeStepTwoTitle: '2. Wählen Sie einen passenden Helfer', homeStepTwoCopy: 'Sehen Sie zuerst Verfügbarkeit, Sprachen und praktische Angaben.', homeStepThreeTitle: '3. Mit Vertrauen bestätigen', homeStepThreeCopy: 'Prüfen Sie den Besuch, bevor Sie Kontaktdaten teilen.',
    homeEveryday: 'Unterstützung im Alltag', homeQuestion: 'Wobei brauchen Sie heute Hilfe?', homeQuestionCopy: 'Wählen Sie eine vertraute Aufgabe. Sie können Helfer vor der Buchung ansehen.', homeSeeServices: 'Alle Dienste ansehen', homeFindHelpers: 'Helfer finden', homeSafetyTitle: 'Klare Sicherheitsinformationen', homeSafetyCopy: 'Helfer müssen die Prüfung vor dem Start eines echten Marktplatzes abschließen.', homeIndependenceTitle: 'Für Selbstständigkeit entwickelt', homeIndependenceCopy: 'Große Bedienelemente, einfache Sprache und immer ein klarer nächster Schritt.', homeNeedBooking: 'Brauchen Sie Hilfe bei der Buchung?', homeCallLine: 'Rufen Sie den Support an:',
    servicesEyebrow: 'Hilfe finden', servicesTitle: 'Wobei brauchen Sie Hilfe?', servicesCopy: 'Wählen Sie einen Dienst, um lokale Helfer zu sehen. Zum Ansehen ist kein Konto nötig.', servicesSeeHelpers: 'Helfer ansehen', servicesUnsure: 'Nicht sicher, welchen Dienst Sie brauchen?', servicesUnsureCopy: 'Rufen Sie uns an – wir helfen Ihnen, die richtige Unterstützung zu wählen.',
    serviceGroceries: 'Einkäufe und Apotheke', serviceGroceriesCopy: 'Einkäufe, Rezepte und wichtige Besorgungen.', serviceCleaning: 'Reinigung und Haushalt', serviceCleaningCopy: 'Leichte Reinigung und praktische Hilfe zu Hause.', serviceCompanionship: 'Besuche und Gesellschaft', serviceCompanionshipCopy: 'Ein freundlicher Besuch, Spaziergang oder Gespräch.', serviceAppointments: 'Begleitung zu Terminen', serviceAppointmentsCopy: 'Begleitung und Fahrhilfe für Termine.', serviceTechnology: 'Technikhilfe', serviceTechnologyCopy: 'Telefone, Computer, Videoanrufe und Geräte.', serviceRepairs: 'Kleine Aufgaben zu Hause', serviceRepairsCopy: 'Leichte Hausarbeiten und kleine Reparaturen.', serviceTransport: 'Fahrten und Transport', serviceTransportCopy: 'Hilfe, um sicher in Ihrer Umgebung unterwegs zu sein.', allServices: 'Alle Dienste', allLanguages: 'Alle Sprachen', communityHelper: 'Helfer aus der Gemeinschaft', identityChecked: 'Identität geprüft', viewHelper: 'Helfer ansehen', requestVisit: 'Besuch anfragen'
  },
  lb: {
    navFindHelp: 'Hëllef fannen', navBookings: 'Meng Buchungen', navBecomeHelper: 'Hëllefer ginn', navHelp: 'Hëllef a Kontakt', callSupport: 'Support uruffen',
    homeBadge: 'Fir den Alldag zu Lëtzebuerg', homeTitle: 'Vertrauenswert lokal Hëllef fir Iech an Är Léifsten.', homeSubtitle: 'Fannt praktesch a frëndlech Ënnerstëtzung aus Ärer Géigend fir alldeeglech Aufgaben, Rendez-vousen, Technik a Gesellschaft.', homeFindHelp: 'Hëllef a menger Géigend fannen', homeBecomeHelper: 'Hëllefer ginn', homeNoAccount: 'Fir ze kucke braucht Dir kee Kont. Mir froen Är Kontaktdonnéeën eréischt wann Dir eng Ufro confirméiert.',
    homeSimpleTitle: 'Einfach, sécher a mënschlech.', homeStepOneTitle: '1. Sot eis wat gebraucht gëtt', homeStepOneCopy: 'Wielt e Service an eng Géigend. Kee Login néideg.', homeStepTwoTitle: '2. Wielt e passenden Hëllefer', homeStepTwoCopy: 'Kuckt fir d’éischt Disponibilitéit, Sproochen a praktesch Detailer.', homeStepThreeTitle: '3. Mat Vertraue confirméieren', homeStepThreeCopy: 'Iwwerpréift de Besuch ier Dir Kontaktdonnéeë deelt.',
    homeEveryday: 'Hëllef am Alldag', homeQuestion: 'Woubei braucht Dir haut Hëllef?', homeQuestionCopy: 'Wielt eng vertraut Aufgab. Dir kënnt Hëllefer kucken ier Dir bucht.', homeSeeServices: 'All Servicer kucken', homeFindHelpers: 'Hëllefer fannen', homeSafetyTitle: 'Kloer Sécherheetsinformatiounen', homeSafetyCopy: 'Hëllefer mussen d’Verifikatioun ofschléissen ier e richtege Service lancéiert gëtt.', homeIndependenceTitle: 'Fir Onofhängegkeet entwéckelt', homeIndependenceCopy: 'Grouss Kontrollflächen, einfach Sprooch an ëmmer ee kloere nächste Schrëtt.', homeNeedBooking: 'Braucht Dir Hëllef beim Buchen?', homeCallLine: 'Rufft de Support un:',
    servicesEyebrow: 'Hëllef fannen', servicesTitle: 'Wéi eng Hëllef braucht Dir?', servicesCopy: 'Wielt e Service fir lokal Hëllefer ze gesinn. Fir ze kucke braucht Dir kee Kont.', servicesSeeHelpers: 'Hëllefer kucken', servicesUnsure: 'Net sécher wéi ee Service passt?', servicesUnsureCopy: 'Rufft eis un a mir hëllefen Iech déi richteg Ënnerstëtzung ze wielen.',
    serviceGroceries: 'Akafen an Apdikt', serviceGroceriesCopy: 'Akafen, Rezepter a wichteg Besuergungen.', serviceCleaning: 'Botzen an Haushalt', serviceCleaningCopy: 'Liicht Botzen a praktesch Hëllef doheem.', serviceCompanionship: 'Besich a Gesellschaft', serviceCompanionshipCopy: 'E frëndleche Besuch, Spadséiergang oder Gespréich.', serviceAppointments: 'Begleedung bei Rendez-vousen', serviceAppointmentsCopy: 'Gesellschaft an Transporthëllef fir Rendez-vousen.', serviceTechnology: 'Tech-Hëllef', serviceTechnologyCopy: 'Telefonen, Computeren, Video-Uriff an Apparater.', serviceRepairs: 'Kleng Aufgaben doheem', serviceRepairsCopy: 'Liicht Hausaufgaben a kleng Reparaturen.', serviceTransport: 'Trajeten an Transport', serviceTransportCopy: 'Hëllef fir sécher an Ärer Géigend ënnerwee ze sinn.', allServices: 'All Servicer', allLanguages: 'All Sproochen', communityHelper: 'Hëllefer aus der Gemeinschaft', identityChecked: 'Identitéit iwwerpréift', viewHelper: 'Hëllefer kucken', requestVisit: 'Besuch ufroen'
  }
}
