'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { ArrowLeft, BadgeCheck, CalendarDays, Globe2, MapPin, ShieldCheck, Wallet } from 'lucide-react'
import { SiteHeader } from '@/components/site-header'
import { getLocalHelpers, type LocalHelper } from '@/lib/community-local'

export default function HelperProfilePage({ params }: { params: Promise<{ id: string }> }) {
  const [helper, setHelper] = useState<LocalHelper | null>(null); const [loaded, setLoaded] = useState(false)
  useEffect(() => { params.then(({ id }) => { setHelper(getLocalHelpers().find((profile) => profile.id === id) ?? null); setLoaded(true) }) }, [params])
  if (!loaded) return <main className="grid min-h-screen place-items-center bg-[#f7fbf9] text-lg">Loading helper profile…</main>
  if (!helper) return <main className="min-h-screen bg-[#f7fbf9]"><SiteHeader/><section className="mx-auto max-w-2xl px-5 py-20 text-center"><h1 className="text-4xl font-extrabold">This helper profile is no longer available.</h1><Link href="/helpers" className="mt-6 inline-flex min-h-12 items-center rounded-xl bg-[#187864] px-5 font-bold text-white">Find helpers</Link></section></main>
  const initials = helper.name.split(' ').map((part) => part[0]).join('').slice(0, 2)
  return <main className="min-h-screen bg-[#f7fbf9] text-[#183d38]"><SiteHeader/><section className="mx-auto max-w-[900px] px-5 py-10"><Link href="/helpers" className="inline-flex min-h-11 items-center gap-2 font-bold text-[#28554d]"><ArrowLeft size={18}/> Back to helpers</Link><div className="mt-6 rounded-[28px] border border-[#d8e7e2] bg-white p-6 shadow-sm sm:p-10"><div className="flex flex-col gap-6 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-center gap-5"><span className="grid h-20 w-20 place-items-center rounded-full bg-[#e7f5ef] text-2xl font-extrabold text-[#187864]">{initials}</span><div><p className="inline-flex items-center gap-1 text-sm font-bold text-[#187864]"><ShieldCheck size={16}/> {helper.verificationStatus === 'identity-checked' ? 'Identity checked' : 'Verification required before launch'}</p><h1 className="mt-2 text-4xl font-extrabold tracking-[-.045em]">{helper.name}</h1><p className="mt-1 text-lg text-[#5b7771]">Community helper in {helper.address}</p></div></div><Link href={`/book/${helper.id}`} className="inline-flex min-h-14 items-center justify-center rounded-xl bg-[#187864] px-6 text-lg font-bold text-white">Request a visit</Link></div><div className="mt-9 grid gap-5 sm:grid-cols-2"><Info icon={<CalendarDays/>} title="Availability" copy={helper.timeAvailableForWork}/><Info icon={<Wallet/>} title="Payment" copy={helper.pay}/><Info icon={<MapPin/>} title="Service area" copy={helper.address}/><Info icon={<Globe2/>} title="Languages spoken" copy={helper.languages?.join(', ') || 'English, French, German'}/></div><div className="mt-8 rounded-2xl bg-[#eff8f4] p-5"><h2 className="text-2xl font-extrabold">About this helper</h2><p className="mt-3 text-lg leading-7 text-[#54746c]">{helper.bio || 'This community helper has shared their availability and local area. Ask for the support you need before confirming a visit.'}</p></div><div className="mt-8 rounded-2xl border border-[#f0d7c8] bg-[#fff6ef] p-5"><p className="flex items-center gap-2 text-lg font-extrabold text-[#76513d]"><BadgeCheck size={20}/> Safety first</p><p className="mt-2 text-base leading-6 text-[#76513d]">Review the visit details before confirming. For an emergency, call 112 or 113 immediately.</p></div></div></section></main>
}

function Info({ icon, title, copy }: { icon: React.ReactNode; title: string; copy: string }) { return <div className="flex gap-3 rounded-2xl border border-[#dceae5] p-4 text-[#187864]"><span className="shrink-0">{icon}</span><p className="text-base text-[#54746c]"><strong className="block text-lg text-[#183d38]">{title}</strong>{copy}</p></div> }
