'use client'

import Link from 'next/link'
import { FormEvent, useState } from 'react'
import { ArrowLeft, ArrowRight, Heart, ShieldCheck } from 'lucide-react'
import { LanguageToggle } from '@/components/language-toggle'
import { useLanguage } from '@/lib/language'
import { saveLocalRequester } from '@/lib/community-local'

type Fields = { name: string; phoneNumber: string; address: string; description: string }
const initial: Fields = { name: '', phoneNumber: '', address: '', description: '' }
const validPhone = (value: string) => { const digits = value.replace(/\D/g, ''); return digits.length >= 6 && digits.length <= 15 }
const validAddress = (value: string) => value.trim().length >= 5 && /\d/.test(value)

export default function RequesterSignupPage() {
  const { t } = useLanguage(); const [fields, setFields] = useState<Fields>(initial); const [errors, setErrors] = useState<Partial<Record<keyof Fields, string>>>({}); const [saving, setSaving] = useState(false); const [serverError, setServerError] = useState(''); const update = (name: keyof Fields, value: string) => setFields({ ...fields, [name]: value })
  const submit = (event: FormEvent) => { event.preventDefault(); const next: Partial<Record<keyof Fields, string>> = {}; (['name', 'phoneNumber', 'address'] as (keyof Fields)[]).forEach((key) => { if (!fields[key].trim()) next[key] = t('required') }); if (fields.phoneNumber && !validPhone(fields.phoneNumber)) next.phoneNumber = t('invalidPhone'); if (fields.address && !validAddress(fields.address)) next.address = t('invalidAddress'); setErrors(next); setServerError(''); if (Object.keys(next).length) return; setSaving(true); try { saveLocalRequester(fields); window.location.assign('/helpers?view=requesters&message=requester-joined') } catch { setServerError('We could not save your details on this device.') } finally { setSaving(false) } }
  const input = (name: keyof Fields, label: string, placeholder: string) => <label className="block"><span className="mb-2 block font-bold text-[#28554d]">{label}</span><input required value={fields[name]} onChange={(e) => update(name, e.target.value)} placeholder={placeholder} className={`w-full rounded-xl border-2 bg-white px-4 py-3.5 text-[16px] outline-none transition placeholder:text-[#9aada8] focus:border-[#187864] ${errors[name] ? 'border-red-400' : 'border-[#d8e7e2]'}`} aria-invalid={Boolean(errors[name])}/>{errors[name] && <span className="mt-1.5 block text-sm font-semibold text-red-600">{errors[name]}</span>}</label>
  return <main className="min-h-screen bg-[#f4f9f7] text-[#183d38]"><header className="mx-auto flex max-w-[1000px] items-center justify-between gap-4 px-5 py-5"><Link href="/" className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#187864] text-white"><Heart size={22} fill="currentColor"/></span><span className="text-xl font-extrabold tracking-[-.04em]">{t('brand')}</span></Link><div className="flex items-center gap-3"><LanguageToggle/><Link href="/" className="flex items-center gap-2 text-sm font-bold text-[#47716a]"><ArrowLeft size={17}/> {t('backHome')}</Link></div></header><section className="mx-auto max-w-[720px] px-5 pb-16 pt-10"><div className="rounded-[28px] border border-[#dceae5] bg-white p-6 shadow-sm sm:p-10"><p className="font-bold uppercase tracking-[.12em] text-sm text-[#e07b4c]">{t('signupFinderEyebrow')}</p><h1 className="mt-2 text-4xl font-extrabold tracking-[-.045em]">{t('signupFinderTitle')}</h1><p className="mt-4 text-[17px] leading-7 text-[#678079]">{t('signupFinderCopy')}</p><form className="mt-8 grid gap-5" onSubmit={submit}>{input('name', t('name'), 'Enter your full name')}{input('phoneNumber', t('phone'), t('phonePlaceholder'))}{input('address', t('address'), t('addressPlaceholder'))}<label className="block"><span className="mb-2 block font-bold text-[#28554d]">{t('helpQuestion')} <span className="font-normal text-[#6f8982]">{t('optional')}</span></span><textarea value={fields.description} onChange={(e) => update('description', e.target.value)} placeholder="Describe the help you need" className="min-h-28 w-full rounded-xl border-2 border-[#d8e7e2] bg-white px-4 py-3.5 text-[16px] outline-none transition placeholder:text-[#9aada8] focus:border-[#187864]"/></label>{serverError && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{serverError}</p>}<button disabled={saving} className="mt-2 flex min-h-14 items-center justify-center gap-2 rounded-xl bg-[#187864] px-5 text-[17px] font-bold text-white disabled:opacity-60">{saving ? 'Saving…' : <>{t('seeHelpers')} <ArrowRight size={19}/></>}</button><p className="flex justify-center gap-1.5 text-center text-xs text-[#718b83]"><ShieldCheck size={15} className="text-[#187864]"/> {t('savedLocally')}</p></form></div></section></main>
}
