'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { CalendarDays, MapPin, Phone, XCircle } from 'lucide-react'
import { SiteHeader } from '@/components/site-header'
import { cancelLocalBooking, getLocalBookings, type LocalBooking } from '@/lib/community-local'

export default function BookingsPage() {
  const [bookings, setBookings] = useState<LocalBooking[]>([])
  useEffect(() => setBookings(getLocalBookings()), [])
  const cancel = (id: string) => { if (!window.confirm('Cancel this visit request?')) return; if (cancelLocalBooking(id)) setBookings(getLocalBookings()) }
  return <main className="min-h-screen bg-[#f7fbf9] text-[#183d38]"><SiteHeader/><section className="mx-auto max-w-[980px] px-5 py-14"><p className="font-bold uppercase tracking-[.12em] text-[#df7648]">Your saved visits</p><h1 className="mt-2 text-5xl font-extrabold tracking-[-.055em]">My bookings</h1><p className="mt-4 max-w-2xl text-xl leading-8 text-[#58746d]">Review your requests, call support, or cancel a visit that is no longer needed.</p>{bookings.length ? <div className="mt-9 grid gap-5">{bookings.map((booking) => <article key={booking.id} className="rounded-2xl border border-[#d8e7e2] bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><span className={`inline-flex rounded-full px-3 py-1 text-sm font-bold ${booking.status === 'cancelled' ? 'bg-red-50 text-red-700' : 'bg-[#e7f5ef] text-[#187864]'}`}>{booking.status === 'cancelled' ? 'Cancelled' : 'Visit requested'}</span><h2 className="mt-4 text-2xl font-extrabold">{booking.service} with {booking.helperName}</h2><p className="mt-1 text-lg text-[#5b7771]">For: {booking.bookedFor}</p></div><a href="tel:+35227123456" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border-2 border-[#c9ddd7] px-4 font-bold text-[#28554d]"><Phone size={18}/> Call support</a></div><div className="mt-6 grid gap-3 border-t border-[#e2ece8] pt-5 text-base text-[#54746c] sm:grid-cols-2"><p className="flex gap-2"><CalendarDays className="text-[#187864]" size={19}/><span><strong className="block text-[#183d38]">When</strong>{booking.date} at {booking.time}</span></p><p className="flex gap-2"><MapPin className="text-[#187864]" size={19}/><span><strong className="block text-[#183d38]">Where</strong>{booking.address}</span></p></div>{booking.notes && <p className="mt-5 rounded-xl bg-[#f7fbf9] p-4 text-base text-[#54746c]"><strong className="text-[#183d38]">Notes: </strong>{booking.notes}</p>}{booking.status !== 'cancelled' && <button onClick={() => cancel(booking.id)} className="mt-6 inline-flex min-h-12 items-center gap-2 rounded-xl border-2 border-red-200 px-4 font-bold text-red-700 hover:bg-red-50"><XCircle size={18}/> Cancel this request</button>}</article>)}</div> : <div className="mt-9 rounded-[28px] border border-[#d8e7e2] bg-white p-10 text-center shadow-sm"><CalendarDays className="mx-auto text-[#187864]" size={42}/><h2 className="mt-5 text-3xl font-extrabold">No bookings yet</h2><p className="mt-3 text-lg text-[#5b7771]">When you request a visit, it will appear here.</p><Link href="/services" className="mt-7 inline-flex min-h-14 items-center rounded-xl bg-[#187864] px-6 text-lg font-bold text-white">Find help</Link></div>}</section></main>
}
