'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import {
  ArrowRight, BadgeCheck, Bot, BrainCircuit, Check, HandHeart, Heart,
  HeartHandshake, Languages, LockKeyhole, Menu, MessageCircle, ShieldCheck,
  Sparkles, Star, X
} from 'lucide-react'
import { getLocalHelpers, getLocalRequester } from '@/lib/community-local'

const categories = [
  { icon: '🛒', title: 'Groceries & errands', note: 'Shopping, pharmacy and parcels', color: 'bg-orange-50' },
  { icon: '💻', title: 'Technology help', note: 'Phones, video calls and devices', color: 'bg-sky-50' },
  { icon: '🚗', title: 'Rides & transport', note: 'Appointments and getting around', color: 'bg-violet-50' },
  { icon: '🪴', title: 'Home & garden', note: 'Small jobs around the home', color: 'bg-emerald-50' },
  { icon: '🐕', title: 'Pet care', note: 'Dog walking and pet support', color: 'bg-amber-50' },
  { icon: '☕', title: 'Company & chats', note: 'A friendly visit nearby', color: 'bg-rose-50' },
]

const sampleHelpers = [
  { initials: 'ML', name: 'Marie L.', task: 'Groceries & companionship', distance: '0.8 km away', rating: '4.9', color: 'bg-[#d7ece5]' },
  { initials: 'DT', name: 'David T.', task: 'Tech support & rides', distance: '1.2 km away', rating: '5.0', color: 'bg-[#f6e4c9]' },
  { initials: 'SA', name: 'Sofia A.', task: 'Garden & home help', distance: '1.6 km away', rating: '4.8', color: 'bg-[#d9e6fb]' },
]

const faqs = [
  ['Who can use Neighbourly?', 'Anyone in Luxembourg who needs a little everyday help, as well as trusted neighbours who want to offer their time and skills.'],
  ['Do I need to be good with technology?', 'No. The experience is built around large buttons, plain language and short forms. A family member can also help you get started.'],
  ['How quickly can I get help?', 'For a simple request, the goal is to show suitable nearby helpers as soon as possible. Urgent or time-sensitive needs are clearly highlighted.'],
  ['Is it safe?', 'The product is designed around identity checks, clear task details, private contact sharing, reporting and safety guidance before a match.'],
  ['Do I have to pay?', 'Helpers can volunteer or agree a price before accepting a task. The cost should always be clear before anything is confirmed.'],
  ['What if I need to cancel?', 'You can let the helper know as soon as possible. Clear updates and a simple cancellation flow help everyone plan with confidence.'],
  ['Can I use French, German or Luxembourgish?', 'Yes. Neighbourly is designed for Luxembourg’s multilingual community, with English, French, German and Luxembourgish in mind.'],
  ['What if something does not feel right?', 'Stop the interaction, use the report option and contact support. In an emergency, always contact local emergency services first.'],
]

function SectionLabel({ children }: { children: React.ReactNode }) {
  return <p className="mb-3 text-sm font-bold uppercase tracking-[.12em] text-[#e07b4c]">{children}</p>
}

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [savedName, setSavedName] = useState('')

  useEffect(() => {
    const requester = getLocalRequester()
    const helper = getLocalHelpers()[0]
    setSavedName(requester?.name ?? helper?.name ?? '')
  }, [])

  return <main className="min-h-screen overflow-hidden bg-[#fcfdfc] text-[#183d38]">
    <a href="#main" className="skip-link">Skip to content</a>

    <header className="mx-auto flex max-w-[1240px] items-center justify-between px-5 py-5 lg:px-8">
      <a className="flex items-center gap-3" href="#top" aria-label="Neighbourly Luxembourg home"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#187864] text-white shadow-sm"><Heart size={23} fill="currentColor" /></span><span className="text-[22px] font-extrabold tracking-[-0.04em] text-[#17453d]">Neighbourly<span className="text-[#de7c4d]">.</span></span></a>
      <nav className="hidden items-center gap-7 text-[15px] font-semibold text-[#47645f] md:flex"><a href="#how" className="hover:text-[#187864]">How it works</a><a href="#ai" className="hover:text-[#187864]">How AI helps</a><a href="#safety" className="hover:text-[#187864]">Safety</a><a href="#faq" className="hover:text-[#187864]">FAQ</a></nav>
      <Link href="/signup-requester" className="hidden rounded-xl bg-[#187864] px-5 py-3 text-sm font-bold text-white shadow-[0_5px_12px_rgba(24,120,100,.2)] transition hover:bg-[#126653] md:block">I need help</Link>
      <button className="grid h-11 w-11 place-items-center rounded-xl bg-[#eff7f4] md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Open navigation">{menuOpen ? <X/> : <Menu/>}</button>
    </header>

    {menuOpen && <div className="mx-5 rounded-2xl border border-[#dbe9e4] bg-white p-4 shadow-lg md:hidden"><div className="grid gap-2 text-center font-semibold"><a href="#how">How it works</a><a href="#ai">How AI helps</a><a href="#safety">Safety</a><a href="#faq">FAQ</a><Link href="/signup-requester" className="mt-2 rounded-xl bg-[#187864] p-3 text-white">I need help</Link><Link href="/signup-helper" className="rounded-xl border-2 border-[#c9ddd7] p-3 text-[#28554d]">I want to help</Link></div></div>}

    <section id="top" className="relative mx-auto max-w-[1240px] px-5 pb-20 pt-12 lg:px-8 lg:pb-28 lg:pt-20" aria-labelledby="hero-title">
      <div className="absolute left-[-10%] top-20 -z-10 h-72 w-72 rounded-full bg-[#dcefe8] blur-3xl opacity-65"/>
      <div className="absolute right-[-8%] top-24 -z-10 h-60 w-60 rounded-full bg-[#fff0e6] blur-3xl opacity-70"/>
      <div className="grid items-center gap-12 lg:grid-cols-[1.06fr_.94fr]">
        <div className="max-w-[680px]">
          <div className="mb-6 inline-flex items-center gap-2 rounded-full bg-[#e7f5ef] px-4 py-2 text-sm font-bold text-[#187864]"><span className="h-2 w-2 rounded-full bg-[#48af7c]"/>{savedName ? `Welcome back, ${savedName.split(' ')[0]}` : 'Built for everyday life in Luxembourg'}</div>
          <h1 id="hero-title" className="max-w-[690px] text-[46px] font-extrabold leading-[1.06] tracking-[-.055em] text-[#173f39] sm:text-[66px]">Get trusted everyday help from <span className="text-[#e87d4e]">local neighbours.</span></h1>
          <p className="mt-6 max-w-[610px] text-[19px] leading-8 text-[#5b7771]">From groceries and pharmacy pickups to tech help, rides and companionship — describe what you need and find the right local helper in minutes.</p>
          <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/signup-requester" className="group flex min-h-14 items-center justify-center gap-3 rounded-xl bg-[#187864] px-6 text-[17px] font-bold text-white shadow-[0_8px_16px_rgba(24,120,100,.22)] transition hover:-translate-y-0.5 hover:bg-[#126653]">I need help <ArrowRight className="transition group-hover:translate-x-1" size={20}/></Link><Link href="/signup-helper" className="flex min-h-14 items-center justify-center gap-3 rounded-xl border-2 border-[#c9ddd7] bg-white px-6 text-[17px] font-bold text-[#28554d] transition hover:border-[#187864]">I want to help <HandHeart size={20} className="text-[#e87d4e]"/></Link></div>
          <p className="mt-4 text-sm font-medium text-[#6a817b]">No password needed for this demo — your details stay saved on this device.</p>
          <div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm font-semibold text-[#466b63]"><span className="flex items-center gap-2"><BadgeCheck size={18} className="text-[#187864]"/> Safety-first product design</span><span className="flex items-center gap-2"><LockKeyhole size={18} className="text-[#187864]"/> Privacy-minded by design</span><span className="flex items-center gap-2"><Languages size={18} className="text-[#187864]"/> EN · FR · DE · LB</span></div>
        </div>
        <div className="relative mx-auto w-full max-w-[510px]">
          <div className="absolute -right-5 top-4 h-[405px] w-[405px] rounded-full bg-[#dcefe8] sm:h-[445px] sm:w-[445px]"/>
          <div className="relative rounded-[34px] border border-[#d3e6df] bg-[#f3faf7] p-5 shadow-[0_24px_50px_rgba(37,86,75,.16)]">
            <div className="rounded-[25px] bg-[#174d43] p-5 text-white"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-[#a8dbcb]">Concept preview</p><p className="mt-1 text-xl font-extrabold">AI-assisted matching</p></div><span className="grid h-11 w-11 place-items-center rounded-2xl bg-white/10"><Sparkles size={22}/></span></div><div className="mt-5 rounded-2xl bg-white/10 p-3 text-sm leading-6 text-[#d7eee7]"><strong className="text-white">“I need groceries on Tuesday afternoon.”</strong><br/>The planned AI workflow turns this into a clear request and suggests suitable local helpers.</div></div>
            <div className="relative -mt-1 grid gap-3 p-3 pt-5">{sampleHelpers.map((helper, index) => <article key={helper.name} className={`flex items-center gap-3 rounded-2xl border border-[#dbe9e4] bg-white p-3 shadow-sm ${index === 2 ? 'opacity-95' : ''}`}><span className={`grid h-12 w-12 place-items-center rounded-full text-sm font-extrabold text-[#214a42] ${helper.color}`}>{helper.initials}</span><span className="min-w-0 flex-1"><span className="flex items-center gap-1 font-extrabold text-[#214a42]">{helper.name}<BadgeCheck size={15} className="text-[#187864]"/></span><span className="mt-0.5 block truncate text-xs text-[#66817b]">{helper.task}</span></span><span className="text-right text-xs font-bold text-[#53736b]"><span className="flex items-center justify-end gap-1"><Star size={13} fill="#e8a54a" className="text-[#e8a54a]"/>{helper.rating}</span><span className="mt-1 block">{helper.distance}</span></span></article>)}</div>
          </div>
          <div className="absolute -bottom-5 -left-4 rounded-2xl border border-[#d8e8e2] bg-white p-3.5 shadow-lg"><div className="flex items-center gap-2.5"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#fff1e9] text-[#de7c4d]"><ShieldCheck size={21}/></span><div><p className="text-xs font-extrabold">Safety comes first</p><p className="text-[11px] text-[#66817b]">Clear tasks. Clear expectations.</p></div></div></div>
        </div>
      </div>
    </section>

    <section className="border-y border-[#e3eeea] bg-[#f4f9f7] py-10"><div className="mx-auto max-w-[1240px] px-5 lg:px-8"><p className="mb-4 text-center text-xs font-bold uppercase tracking-[.12em] text-[#77938b]">Demo design goals</p><div className="grid gap-5 text-center sm:grid-cols-3"><div><p className="text-2xl font-extrabold text-[#174d43]">2 minutes</p><p className="mt-1 text-sm text-[#66817b]">to describe a simple task</p></div><div className="border-[#d7e7e1] sm:border-x"><p className="text-2xl font-extrabold text-[#174d43]">4 languages</p><p className="mt-1 text-sm text-[#66817b]">designed into the experience</p></div><div><p className="text-2xl font-extrabold text-[#174d43]">Safety-first</p><p className="mt-1 text-sm text-[#66817b]">matching and support model</p></div></div></div></section>

    <section id="main" className="mx-auto max-w-[1240px] px-5 py-20 lg:px-8" aria-labelledby="help-title"><div className="mb-10 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><SectionLabel>Everyday help, made simple</SectionLabel><h2 id="help-title" className="text-4xl font-extrabold tracking-[-.04em]">What can a neighbour help with?</h2><p className="mt-3 max-w-2xl text-[17px] leading-7 text-[#678079]">Choose a familiar task, describe it in your own words, and keep control of what happens next.</p></div><Link href="/signup-requester" className="flex w-fit items-center gap-2 font-bold text-[#187864] hover:underline">Tell us what you need <ArrowRight size={18}/></Link></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{categories.map((item) => <Link href="/signup-requester" key={item.title} className="group flex items-center gap-4 rounded-2xl border border-[#dfebe7] bg-white p-5 text-left shadow-sm transition hover:-translate-y-1 hover:border-[#9ac6b8] hover:shadow-md"><span className={`grid h-14 w-14 shrink-0 place-items-center rounded-2xl text-3xl ${item.color}`}>{item.icon}</span><span><span className="block text-[17px] font-extrabold text-[#214a42]">{item.title}</span><span className="mt-1 block text-sm text-[#68807a]">{item.note}</span></span><ArrowRight className="ml-auto text-[#9db7b0] transition group-hover:translate-x-1 group-hover:text-[#187864]" size={20}/></Link>)}</div></section>

      <section id="how" className="border-y border-[#e3eeea] bg-[#f4f9f7] py-20"><div className="mx-auto max-w-[1240px] px-5 lg:px-8"><div className="max-w-2xl"><SectionLabel>How it works</SectionLabel><h2 className="text-4xl font-extrabold leading-tight tracking-[-.045em]">Clear help in three simple steps.</h2><p className="mt-4 text-[17px] leading-7 text-[#66817b]">Made for people who want a simple process, not another complicated app.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[['01', 'Tell us what you need', 'Type or say it naturally: “I need help collecting my prescription tomorrow.”'], ['02', 'See a clear task', 'The planned AI workflow organises the task into a category, time, location and safety notes.'], ['03', 'Choose your next step', 'Review suitable local helpers, agree expectations and stay in control.']].map(([number, title, copy]) => <article key={number} className="rounded-2xl border border-[#dfece7] bg-white p-6 shadow-sm"><span className="text-4xl font-extrabold text-[#c5e2d8]">{number}</span><h3 className="mt-12 text-xl font-extrabold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#69817b]">{copy}</p></article>)}</div><div className="mt-8 grid gap-3 rounded-[24px] bg-white p-5 shadow-sm md:grid-cols-3"><div><p className="font-extrabold text-[#214a42]">How quickly can I get help?</p><p className="mt-1 text-sm leading-6 text-[#69817b]">Simple requests can be prepared in minutes; availability depends on nearby helpers.</p></div><div><p className="font-extrabold text-[#214a42]">Is it safe?</p><p className="mt-1 text-sm leading-6 text-[#69817b]">The product design prioritises checks, clear task details and a simple way to report concerns.</p></div><div><p className="font-extrabold text-[#214a42]">How does payment work?</p><p className="mt-1 text-sm leading-6 text-[#69817b]">Volunteer or paid help is agreed clearly before a task is accepted.</p></div></div></div></section>

    <section className="mx-auto max-w-[1240px] px-5 py-20 lg:px-8"><div className="grid gap-6 lg:grid-cols-2"><article className="rounded-[30px] bg-[#e7f5ef] p-7 sm:p-10"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-white text-[#187864] shadow-sm"><HeartHandshake size={29}/></span><SectionLabel>For people looking for help</SectionLabel><h2 className="text-3xl font-extrabold tracking-[-.04em]">Keep your independence, with a little support nearby.</h2><p className="mt-4 max-w-lg text-[17px] leading-7 text-[#58736c]">Ask for practical help without having to explain an app to someone else. Start with what you need today.</p><ul className="mt-6 grid gap-3 text-[#315a51]">{['Describe a task in your own words', 'Find help for errands, tech, transport or companionship', 'Know the task and expectations before you agree', 'Use an experience designed with accessibility in mind'].map((item) => <li key={item} className="flex gap-3"><Check size={20} className="mt-0.5 shrink-0 text-[#187864]"/>{item}</li>)}</ul><Link href="/signup-requester" className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-xl bg-[#187864] px-5 font-bold text-white">I need help <ArrowRight size={18}/></Link></article><article className="rounded-[30px] bg-[#fff3eb] p-7 sm:p-10"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-white text-[#de7c4d] shadow-sm"><HandHeart size={29}/></span><SectionLabel>For local helpers</SectionLabel><h2 className="text-3xl font-extrabold tracking-[-.04em]">Turn a spare hour into meaningful local impact.</h2><p className="mt-4 max-w-lg text-[17px] leading-7 text-[#6f675f]">Offer a skill, a ride or a friendly visit at times that suit you. Volunteer your time or agree a fair price upfront.</p><ul className="mt-6 grid gap-3 text-[#5f5148]">{['Choose the kind of help you are comfortable offering', 'Set availability that fits around your life', 'Volunteer or agree transparent pay before a task', 'Complete a clear onboarding and verification journey'].map((item) => <li key={item} className="flex gap-3"><Check size={20} className="mt-0.5 shrink-0 text-[#de7c4d]"/>{item}</li>)}</ul><div className="mt-6 rounded-2xl bg-white/70 p-4 text-sm leading-6 text-[#6f675f]"><strong className="text-[#5f5148]">Helper flow:</strong> Choose what you can offer → set your available time → review a clear task before saying yes.</div><Link href="/signup-helper" className="mt-6 inline-flex min-h-12 items-center gap-2 rounded-xl bg-[#de7c4d] px-5 font-bold text-white">I want to help <ArrowRight size={18}/></Link></article></div></section>

    <section id="ai" className="bg-[#173f39] py-20 text-white"><div className="mx-auto grid max-w-[1240px] gap-12 px-5 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div><div className="inline-flex items-center gap-2 rounded-full bg-white/10 px-4 py-2 text-sm font-bold text-[#bce6d8]"><Sparkles size={17}/> AI that makes help easier</div><h2 className="mt-5 text-4xl font-extrabold leading-tight tracking-[-.045em]">Useful AI, not a gimmick.</h2><p className="mt-5 max-w-md text-[17px] leading-7 text-[#c5dcd6]">Neighbourly is designed to turn a confusing request into a clear next step — making it easier to ask for help and easier to offer it safely.</p><p className="mt-6 text-sm leading-6 text-[#a4c7bc]">Built for an OpenAI Build Week demo: practical assistance, human decision-making and clear boundaries.</p></div><div className="grid gap-4 md:grid-cols-3">{[[Bot, 'Clearer requests', 'Turn free text or voice into a structured task with a suggested category, time and location.'], [BrainCircuit, 'Better matches', 'Suggest helpers using skills, availability, proximity and community reliability signals.'], [ShieldCheck, 'Plain-language safety', 'Summarise the key safety guidance for each task so both people know what to expect.']].map(([Icon, title, copy]) => { const FeatureIcon = Icon as typeof Bot; return <article key={title as string} className="rounded-2xl border border-white/10 bg-white/5 p-6"><FeatureIcon className="text-[#9cddc8]" size={28}/><h3 className="mt-10 text-xl font-extrabold">{title as string}</h3><p className="mt-3 text-sm leading-6 text-[#bed5cf]">{copy as string}</p></article> })}</div></div></section>

    <section id="community" className="mx-auto max-w-[1240px] px-5 py-20 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><SectionLabel>Community trust</SectionLabel><h2 className="text-4xl font-extrabold leading-tight tracking-[-.045em]">Designed to feel safe, local and human.</h2><p className="mt-5 max-w-md text-[17px] leading-7 text-[#66817b]">A strong community is built with clear standards, not vague promises. Neighbourly is designed around respectful communication, visible expectations and support when needed.</p><div className="mt-8 grid gap-3 text-sm font-bold text-[#315a51]"><span className="flex items-center gap-2"><BadgeCheck size={19} className="text-[#187864]"/> ID-check and verification workflow</span><span className="flex items-center gap-2"><LockKeyhole size={19} className="text-[#187864]"/> Addresses are not shared publicly</span><span className="flex items-center gap-2"><MessageCircle size={19} className="text-[#187864]"/> Reporting and support pathways</span></div></div><div className="grid gap-3 sm:grid-cols-3">{sampleHelpers.map((helper) => <article key={helper.name} className="rounded-2xl border border-[#dbe9e4] bg-white p-5 shadow-sm"><span className={`grid h-14 w-14 place-items-center rounded-full text-sm font-extrabold ${helper.color}`}>{helper.initials}</span><p className="mt-4 font-extrabold">{helper.name}</p><p className="mt-1 text-xs leading-5 text-[#6a817b]">{helper.task}</p><div className="mt-5 border-t pt-3"><div className="flex items-center gap-1 text-xs font-bold"><Star size={14} fill="#e8a54a" className="text-[#e8a54a]"/>{helper.rating}<span className="ml-auto text-[#6c857e]">{helper.distance}</span></div></div><div className="mt-3 inline-flex items-center gap-1 text-[11px] font-bold text-[#187864]"><ShieldCheck size={14}/> Example profile</div></article>)}</div></div></section>

    <section id="safety" className="bg-[#f4f9f7] py-20"><div className="mx-auto max-w-[1000px] px-5 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#e7f5ef] text-[#187864]"><ShieldCheck size={29}/></span><h2 className="mt-5 text-4xl font-extrabold tracking-[-.04em]">Help with heart. Safety from the start.</h2><p className="mx-auto mt-4 max-w-2xl text-[17px] leading-7 text-[#66817b]">From verification checks to reporting pathways, Neighbourly is designed so people can make informed choices. It welcomes multilingual, diverse neighbours across Luxembourg — with dignity and kindness at the centre.</p><div className="mt-10 grid gap-3 text-left sm:grid-cols-3">{[['Verification first', 'A clear onboarding process makes trust visible before people meet.'], ['Private by default', 'Only share the details needed for a specific request and next step.'], ['Support when needed', 'Simple reporting, safety reminders and clear guidance keep people in control.']].map(([title, copy]) => <article key={title} className="rounded-2xl bg-white p-5 shadow-sm"><Check className="text-[#187864]"/><h3 className="mt-4 font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#69817b]">{copy}</p></article>)}</div></div></section>

    <section className="mx-auto max-w-[1240px] px-5 py-20 lg:px-8"><div className="text-center"><SectionLabel>What a community could say</SectionLabel><h2 className="text-4xl font-extrabold tracking-[-.04em]">Small moments of help matter.</h2><p className="mx-auto mt-4 max-w-2xl text-[17px] leading-7 text-[#678079]">Illustrative feedback for the Neighbourly demo — grounded in the kind of everyday support the platform aims to create.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[['“I only needed help setting up a video call. It felt simple, respectful and not at all embarrassing.”', 'Elise, Kirchberg'], ['“I can offer one or two hours at weekends. It is a small commitment that can make someone’s whole week easier.”', 'Nicolas, Esch-sur-Alzette'], ['“The clear task details made it easy to know what was needed before I said yes.”', 'Sofia, Belair']].map(([quote, name]) => <figure key={name} className="rounded-2xl border border-[#dceae5] bg-white p-6 shadow-sm"><div className="flex gap-1 text-[#e8a54a]">{Array.from({ length: 5 }).map((_, index) => <Star key={index} size={16} fill="currentColor"/>)}</div><blockquote className="mt-5 text-[17px] font-semibold leading-7 text-[#315a51]">{quote}</blockquote><figcaption className="mt-5 text-sm font-bold text-[#6a817b]">{name}</figcaption></figure>)}</div></section>

    <section id="faq" className="border-t border-[#e3eeea] bg-[#f4f9f7] py-20"><div className="mx-auto max-w-[900px] px-5"><div className="text-center"><SectionLabel>Questions, answered</SectionLabel><h2 className="text-4xl font-extrabold tracking-[-.04em]">Frequently asked questions</h2><p className="mt-4 text-[17px] text-[#678079]">Simple answers for a simple service.</p></div><div className="mt-10 grid gap-3">{faqs.map(([question, answer]) => <details key={question} className="group rounded-2xl border border-[#dbe9e4] bg-white px-5 py-4 shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-extrabold text-[#214a42]">{question}<span className="text-2xl font-normal text-[#187864] transition group-open:rotate-45">+</span></summary><p className="max-w-3xl pt-4 leading-7 text-[#678079]">{answer}</p></details>)}</div></div></section>

    <section className="bg-[#de7c4d] py-16 text-white"><div className="mx-auto flex max-w-[1000px] flex-col items-center justify-between gap-6 px-5 text-center sm:flex-row sm:text-left"><div><p className="text-sm font-bold uppercase tracking-[.12em] text-[#fff1e9]">Start with one small task</p><h2 className="mt-2 text-3xl font-extrabold tracking-[-.04em]">A little help can change a whole day.</h2></div><Link href="/signup-requester" className="inline-flex min-h-14 shrink-0 items-center gap-2 rounded-xl bg-white px-6 text-[17px] font-bold text-[#b65329] shadow-lg">I need help <ArrowRight size={20}/></Link></div></section>

    <footer className="bg-[#143f37] text-white"><div className="mx-auto max-w-[1240px] px-5 py-12 lg:px-8"><div className="flex flex-col justify-between gap-8 md:flex-row"><div><div className="flex items-center gap-2 text-lg font-extrabold"><Heart size={20} fill="#e87d4e" className="text-[#e87d4e]"/> Neighbourly Luxembourg</div><p className="mt-3 max-w-sm text-sm leading-6 text-[#bed5cf]">Everyday help, made more human — for neighbours across Luxembourg.</p><a className="mt-4 inline-block text-sm font-bold text-[#d7eee7] hover:text-white" href="mailto:hello@neighbourly.lu">hello@neighbourly.lu</a></div><div className="grid grid-cols-2 gap-x-10 gap-y-3 text-sm text-[#d7eee7]"><a href="#how">How it works</a><a href="#safety">Safety</a><a href="#faq">FAQ</a><a href="mailto:hello@neighbourly.lu">Contact</a><a href="#top">Privacy</a><a href="#top">Terms</a></div></div><div className="mt-10 flex flex-col justify-between gap-4 border-t border-white/10 pt-6 text-xs text-[#a4c7bc] sm:flex-row sm:items-center"><p>© 2026 Neighbourly Luxembourg</p><div className="flex items-center gap-2"><span>Language:</span><button className="rounded bg-white/10 px-2 py-1 font-bold text-white">EN</button><button className="px-2 py-1">FR</button><button className="px-2 py-1">DE</button><button className="px-2 py-1">LB</button></div></div></div></footer>

    <Link href="/signup-requester" className="fixed bottom-5 right-5 z-20 grid h-14 w-14 place-items-center rounded-full bg-[#e97e4f] text-white shadow-xl transition hover:scale-105" aria-label="I need help"><MessageCircle size={24}/></Link>
  </main>
}
